<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mimer.Framework\Mimer.Framework.csproj" />
    <ProjectReference Include="..\Mimer.Notes.Model\Mimer.Notes.Model.csproj" />
    <ProjectReference Include="..\Mimer.Notes.Server\Mimer.Notes.Server.csproj" />
  </ItemGroup>

</Project>
